In [ ]:
import numpy as np

In [ ]:
phases = np.array([
    [
        (k*n) for k in range(4)
    ]
    for n in range(4)
])/4

In [ ]:
phases

array([[0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.25, 0.5 , 0.75],
       [0.  , 0.5 , 1.  , 1.5 ],
       [0.  , 0.75, 1.5 , 2.25]])

In [ ]:
Vn = np.exp(-1j*2*np.pi*phases)
np.around(Vn, 2)

array([[ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  0.-1.j, -1.-0.j, -0.+1.j],
       [ 1.+0.j, -1.-0.j,  1.+0.j, -1.-0.j],
       [ 1.+0.j, -0.+1.j, -1.-0.j,  0.-1.j]])

In [ ]:
phases = np.array([
    [
        (k*n) for k in range(5)
    ]
    for n in range(5)
])/5

In [ ]:
Vn = np.exp(-1j*2*np.pi*phases)
np.around(Vn, 2)

array([[ 1.  +0.j  ,  1.  +0.j  ,  1.  +0.j  ,  1.  +0.j  ,  1.  +0.j  ],
       [ 1.  +0.j  ,  0.31-0.95j, -0.81-0.59j, -0.81+0.59j,  0.31+0.95j],
       [ 1.  +0.j  , -0.81-0.59j,  0.31+0.95j,  0.31-0.95j, -0.81+0.59j],
       [ 1.  +0.j  , -0.81+0.59j,  0.31-0.95j,  0.31+0.95j, -0.81-0.59j],
       [ 1.  +0.j  ,  0.31+0.95j, -0.81+0.59j, -0.81-0.59j,  0.31-0.95j]])

In [ ]:
x = np.array([0, 1, 2, 3, 0])

In [ ]:
np.matmul(Vn, x)

array([ 6.        +0.j        , -3.73606798-0.36327126j,
        0.73606798-1.53884177j,  0.73606798+1.53884177j,
       -3.73606798+0.36327126j])

In [ ]:
from scipy.fft import fft
fft(x)

array([ 6.        -0.j        , -3.73606798-0.36327126j,
        0.73606798-1.53884177j,  0.73606798+1.53884177j,
       -3.73606798+0.36327126j])

In [ ]:
D2 = np.zeros(shape=(5, 5))
for i in range(5):
  D2[i, i] = -2
  D2[i, (i+1) % 5] = +1
  D2[(i+1) % 5, i] = +1
D2

array([[-2.,  1.,  0.,  0.,  1.],
       [ 1., -2.,  1.,  0.,  0.],
       [ 0.,  1., -2.,  1.,  0.],
       [ 0.,  0.,  1., -2.,  1.],
       [ 1.,  0.,  0.,  1., -2.]])

In [ ]:
diag = np.matmul(np.linalg.inv(Vn), np.matmul(D2, Vn))

In [ ]:
np.around(diag, 2)

array([[ 0.  +0.j, -0.  -0.j,  0.  -0.j, -0.  -0.j,  0.  -0.j],
       [ 0.  +0.j, -1.38-0.j, -0.  -0.j, -0.  -0.j, -0.  -0.j],
       [ 0.  +0.j, -0.  +0.j, -3.62+0.j,  0.  +0.j, -0.  +0.j],
       [ 0.  +0.j,  0.  -0.j, -0.  +0.j, -3.62-0.j,  0.  +0.j],
       [ 0.  +0.j,  0.  +0.j,  0.  +0.j,  0.  -0.j, -1.38-0.j]])

In [ ]:
Vn_inv = np.exp(+1j*2*np.pi*phases)
id = np.matmul(Vn, Vn_inv)
np.around(id, 2)

array([[ 5.+0.j, -0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [-0.-0.j,  5.+0.j, -0.+0.j, -0.+0.j,  0.+0.j],
       [ 0.-0.j, -0.-0.j,  5.+0.j,  0.+0.j, -0.+0.j],
       [ 0.-0.j, -0.-0.j,  0.-0.j,  5.+0.j, -0.+0.j],
       [ 0.-0.j,  0.-0.j, -0.-0.j, -0.-0.j,  5.+0.j]])